// ─────────────────────────────────────────────────────────────
//  출처 목록 (동작 연구 PM). 클립 JSON 의 sources 칸이 이 id 를 가리킨다.
//  kind: manual(교본 원문·도판) · translation(번역·해설) · mocap(모션 캡처 논문) · dataset(공개 데이터) · biomech(스포츠 생체역학) · estimate(추정)
//  read: 우리가 실제로 읽은 깊이 — 'snippet'(검색 요약), 'abstract'(초록), 'full'(본문), 'memory'(확인 전 기억)
//  license: 이용 조건 (확인한 범위)
// ─────────────────────────────────────────────────────────────
export const SOURCES = {
  meyer_zornhut: {
    kind: 'translation',
    cite: 'Joachim Meyer, Gründtliche Beschreibung der Kunst des Fechtens (1570), Forgeng 역 The Art of Combat (2006) — 분노의 자세',
    quote: '"stand with your left foot forward, and hold your sword on your right shoulder, such that the blade hangs down behind prepared for a stroke."',
    url: 'https://wiktenauer.com/wiki/Joachim_Meyer',
    read: 'snippet',
    license: '원문(1570) 퍼블릭 도메인. Forgeng 번역은 저작권 있음 — 짧은 인용만',
  },
  meyer_zornhau: {
    kind: 'translation',
    cite: 'Meyer 1570 — 네 곧은 베기(Oberhau·Zornhau·Mittelhau·Unterhau) 가운데 Zornhau: 오른 어깨에서 상대 왼쪽 귀로, 또는 얼굴·가슴을 지나는 사선 베기',
    url: 'https://grauenwolf.wordpress.com/2012/06/04/meyers-longsword-the-four-straight-cuts/',
    read: 'snippet',
    license: '해설 블로그 — 인용만',
  },
  meyer_master: {
    kind: 'translation',
    cite: 'Meyer 1570 — 다섯 비밀 베기(Zorn·Krump·Zwerch·Schiel·Scheitel)는 "모든 참된 기술의 뿌리"',
    url: 'https://wiktenauer.com/wiki/Joachim_Meyer',
    read: 'snippet',
    license: '원문 퍼블릭 도메인, 번역 저작권 있음',
  },
  meyer_step: {
    kind: 'translation',
    cite: 'Meyer 1570 발놀림 — "모든 베기는 제 걸음을 가지며, 베기와 같은 때에 딛는다"',
    url: 'https://scholarvictoria.com/2016/02/25/back-to-basics-1-footwork-in-meyer',
    read: 'snippet',
    license: '해설 — 인용만',
  },
  doebringer_step: {
    kind: 'translation',
    cite: 'Pseudo-Hans Döbringer (1389) 주해, David Lindholm 역 — "왼발을 앞에 두고 오른쪽에서 벨 때 오른발로 따라 내딛지 않으면 그 베기는 틀렸다"',
    url: 'https://wiktenauer.com/wiki/Pseudo-Hans_Döbringer/David_Lindholm_LS_2005',
    read: 'snippet',
    license: '원문 퍼블릭 도메인. 번역 이용 조건은 Wiktenauer 토론 페이지 표에 있음(미확인)',
  },
  ringeck_zornhau: {
    kind: 'translation',
    cite: 'Sigmund Ringeck 주해, Christian Trosclair 역 — "상대가 오른쪽에서 위로 베어 오면 너도 오른 어깨에서 앞날로 세게 분노의 베기를 함께 베어라. 상대가 칼에 약하면 칼끝을 길게 얼굴로 쏘아라"',
    url: 'https://wiktenauer.com/wiki/Sigmund_ain_Ringeck/Christian_Trosclair',
    read: 'snippet',
    license: '원문 퍼블릭 도메인, 번역 조건 미확인',
  },
  zettel_verses: {
    kind: 'manual',
    cite: 'Liechtenauer Zettel (14세기) 다섯 베기 구절 — "Krump auf behende, wirf den Ort auf die Hände" · "Zwerch benimmt, was vom Tag dar kommt" · "Schieler bricht, was Büffel schlägt oder sticht" · "Der Scheitler mit seiner Kehr, dem Antlitz ist er gefähr"',
    url: 'https://wiktenauer.com/wiki/Johannes_Liechtenauer',
    read: 'memory',
    license: '퍼블릭 도메인',
  },
  gloss_zwerch: {
    kind: 'translation',
    cite: 'Liechtenauer 주해(Ringeck·Danzig) — Zwerchhau: 칼자루를 머리 앞 높이 들고 엄지를 칼 면 아래에 대고, 뒷날로 가로 벤다. 옆으로 딛는다',
    url: 'https://wiktenauer.com/wiki/Zwerchhau',
    read: 'memory',
    license: '원문 퍼블릭 도메인',
  },
  gloss_schiel: {
    kind: 'translation',
    cite: 'Liechtenauer 주해 — Schielhau: 오른쪽에서 뒷날로 상대 오른 어깨·칼 위를 팔을 뻗어 벤다',
    url: 'https://wiktenauer.com/wiki/Schielhau',
    read: 'memory',
    license: '원문 퍼블릭 도메인',
  },
  gloss_scheitel: {
    kind: 'translation',
    cite: 'Liechtenauer 주해 — Scheitelhau: 머리 위에서 세로로, 팔을 높이 뻗어 앞날로 정수리를 벤다. 칼끝이 얼굴·가슴 쪽으로 늘어진다',
    url: 'https://wiktenauer.com/wiki/Scheitelhau',
    read: 'memory',
    license: '원문 퍼블릭 도메인',
  },
  gloss_krump: {
    kind: 'translation',
    cite: 'Liechtenauer 주해 — Krumphau: 오른발로 상대 오른쪽으로 넓게 딛으며 팔을 엇걸어 칼끝을 상대 손 위로 던진다',
    url: 'https://wiktenauer.com/wiki/Krumphau',
    read: 'memory',
    license: '원문 퍼블릭 도메인',
  },
  meyer_diagram: {
    kind: 'manual',
    cite: 'Meyer 1570 베기 그림 — 세로(Scheitel)·가로(Mittel/Zwerch)·사선 두 줄(Ober·Unter / Zorn) 선의 네모·십자 도형',
    url: 'https://grauenwolf.wordpress.com/2015/11/29/meyers-rapierannotated-cutting-diagrams/',
    read: 'snippet',
    license: '원문 도판 퍼블릭 도메인',
  },
  golf_sequence: {
    kind: 'biomech',
    cite: 'Cheetham 외 2008 (골프 프로 vs 아마추어 운동 사슬): 프로는 골반 → 가슴 → 팔 → 채 순서로 최고 각속도, 팔→채 간격이 골반→팔 간격의 2배 이상. 골반 480±82, 가슴 605±87, 앞팔 1310±236 °/s (다른 연구)',
    url: 'https://www.researchgate.net/publication/252236426',
    read: 'snippet',
    license: '논문 수치 인용',
  },
  golf_xfactor: {
    kind: 'biomech',
    cite: 'TPI 예시: 어깨 90° · 골반 50° → X-factor 40°. Cheetham 2001 X-factor stretch: 내려치기 시작 때 숙련자는 X-factor 를 19% 더 벌린다',
    url: 'https://www.mytpi.com/articles/biomechanics/the-difference-between-x-factor-and-x-factor-stretch',
    read: 'snippet',
    license: '인용',
  },
  baseball_sequence: {
    kind: 'biomech',
    cite: 'Welch 외 1995 JOSPT 22(5) 야구 타격: 골반 최고 714 °/s → 어깨 937 °/s. Escamilla 2009: 성인 윗몸 857 °/s, 배트 30 m/s',
    url: 'https://www.jospt.org/doi/10.2519/jospt.1995.22.5.193',
    read: 'snippet',
    license: '인용',
  },
  swordstem_speed: {
    kind: 'biomech',
    cite: 'SwordSTEM (Sean Franklin) "How fast do swords move": 힘 뺀 오른쪽 내려베기, 베는 부분 최고 약 20 m/s, 닿기 몇 인치 앞에서 최고',
    url: 'https://swordstem.com/2018/08/22/how-fast-do-swords-move-try-1/',
    read: 'snippet',
    license: '인용',
  },
  arma_speed: {
    kind: 'biomech',
    cite: 'George Turner (ARMA) "Sword Motions and Impacts": 롱소드 칼끝 약 75 mph (≈33.5 m/s) 고속 촬영',
    url: 'https://thearma.org/spotlight/GTA/motions_and_impacts.htm',
    read: 'snippet',
    license: '인용',
  },
  aaos_rom: {
    kind: 'biomech',
    cite: 'AAOS 관절 가동 범위 (1965, Greene & Heckman 1994): 어깨 굽힘·벌림 180°, 팔꿈치 150°, 손목 굽힘 80°·폄 70°, 가슴허리 돌림 45°, 엉덩이 안쪽·바깥 돌림 45°',
    url: 'https://link.springer.com/article/10.1186/s12891-020-03665-9',
    read: 'snippet',
    license: '인용',
  },
  mocap_5mudm: {
    kind: 'mocap',
    cite: 'Klempous·Kluwak·Kulbacki·Rozenblit 외, 독일 롱소드 다섯 비밀 베기 모캡 (PJAIT HML, Vicon Plug-in Gait 39 마커 + 근전도 16; IEEE CINTI 2021 / EUROCAST 2022 LNCS 13789)',
    url: 'https://doi.org/10.1007/978-3-031-25312-6_59',
    read: 'abstract',
    license: '공개 안 됨 — "HML 에 요청하면 접근 가능". 요청(저자·기관 연락)은 사장님 허락 뒤',
  },
  mocap_sose2020: {
    kind: 'mocap',
    cite: 'Grontman 외, "Analysis of sword fencing training evaluation possibilities using Motion Capture techniques", IEEE SoSE 2020 — Zwerchhau·Schielhau 칼끝 마커 궤적 그림, 4명(전문 1)',
    url: 'https://ieeexplore.ieee.org/document/9130469/',
    read: 'abstract',
    license: '논문 — 그림 수치 인용만',
  },
  cmu_02: {
    kind: 'dataset',
    cite: 'CMU Graphics Lab Motion Capture, subject 02 trial 07·08·09 "swordplay" (120 Hz)',
    url: 'http://mocap.cs.cmu.edu/',
    read: 'snippet',
    license: '연구·상업 제품 포함 사용 가능, 데이터 자체 재판매 금지(변환본 포함), 출처 표기 요청. 유파 검술 아님',
  },
  fencing_review: {
    kind: 'biomech',
    cite: 'Chen 외 2017 "Biomechanics of fencing sport: A scoping review" (PLoS ONE 12(2) e0171578): 숙련자는 팔이 발보다 먼저, 손-발 시간차 0.07±0.05 s (초보 0.13±0.15 s)',
    url: 'https://doi.org/10.1371/journal.pone.0171578',
    read: 'search-summary',
    license: '인용 (CC BY, 본문은 네트워크 정책으로 못 읽음)',
  },
  fencing_gholipour: {
    kind: 'biomech',
    cite: 'Gholipour 외 2008 펜싱 런지 입체 촬영: 엉덩관절 굽힘 숙련 53° / 초보 40°, 앞무릎 처음 굽힘 약 20° → 폄 51±9° (초보 38° → 18±8°)',
    url: 'https://joh.ut.ac.ir/article_26965.html',
    read: 'search-summary',
    license: '인용',
  },
  fencing_mulloy: {
    kind: 'biomech',
    cite: 'Mulloy 외 ISBS "Use of the kinematic chain in the fencing attacking lunge": 숙련자 뒷다리 엉덩이→무릎→발목 순서, 뒷발목 폄 564±132 °/s (초보 273±184)',
    url: 'https://ojs.ub.uni-konstanz.de/cpa/article/view/6606',
    read: 'search-summary',
    license: '인용',
  },
  fencing_lunge: {
    kind: 'biomech',
    cite: 'ISBS 엘리트 펜싱 런지: 길이 1.24 m (0.88~1.86), 엉덩이 속도 1.97 m/s, 몸통 앞기울기 17.5°',
    url: 'https://ojs.ub.uni-konstanz.de/cpa/article/view/3742',
    read: 'snippet',
    license: '인용',
  },
  kendo_men: {
    kind: 'biomech',
    cite: '검도 머리치기: 8단 10명 모캡(Murase 외 ISBS 2020, 수치는 초록에 없음). 대학 선수 머리치기 총 0.818±0.085 s (Sports Biomechanics 2026)',
    url: 'https://commons.nmu.edu/isbs/vol38/iss1/135/',
    read: 'abstract',
    license: '인용',
  },
  estimate: {
    kind: 'estimate',
    cite: '동작 연구 PM 추정 — 게임 뼈대 치수·교본 자세·생체역학 범위 안에서 정함',
    url: '',
    read: 'full',
    license: '우리 것',
  },
};
